---
- name: Ensure we are using pacman
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use pacman as a package manager."
  when: ansible_pkg_mgr != "pacman"

- name: Checks gpg version in package manager
  when: gpg_distro_pkgs is defined and gpg_distro_pkgs | length > 0
  block:
    - name: Update pacman cache
      community.general.pacman:
        update_cache: true
      changed_when: false # The pacman module currently does not support cache_valid_time.
      become: true

    - name: Get gpg version from package manager
      ansible.builtin.command:
        cmd: "pacman -Si {{ gpg_distro_pkgs[0] }}"
      changed_when: false
      failed_when: false
      ignore_errors: true
      register: gpg_pkg_mgr_version_cmd

    - name: Extract only the version into a variable
      ansible.builtin.set_fact:
        gpg_pkg_mgr_version: "{{ (gpg_pkg_mgr_version_cmd.stdout | regex_search('Version.*?([\\d\\.]+)', '\\1', multiline=True))[0] }}"

    - name: Debug gpg version from package manager
      ansible.builtin.debug:
        var: gpg_pkg_mgr_version
