---
- name: Ensure we are using apt
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apt as a package manager."
  when: ansible_pkg_mgr != "apt"

- name: Install gpg dependencies via apt
  when: gpg_distro_pkgs is defined and gpg_distro_pkgs | length > 0
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

    - name: Get gpg version from package manager
      ansible.builtin.command:
        cmd: "apt show {{ gpg_distro_pkgs[0] }}"
      changed_when: false
      failed_when: false
      ignore_errors: true
      register: gpg_pkg_mgr_version_cmd

    - name: Extract only the version into a variable
      ansible.builtin.set_fact:
        gpg_pkg_mgr_version: "{{ (gpg_pkg_mgr_version_cmd.stdout | regex_search('Version:\\ ([\\d\\.]+)', '\\1', multiline=True))[0] }}"

    - name: Debug gpg version from package manager
      ansible.builtin.debug:
        var: gpg_pkg_mgr_version
